name: whichgame
description: A new Flutter project.

version: 1.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0


  cupertino_icons: ^1.0.2
  lottie: ^2.2.0
  flutter_native_splash: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_native_splash:
 color: "#42a5f5"
 image: images/logo.png
 android_gravity: center

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "asset/launcher.png"
  image_path_ios: "asset/launcherr.jpg"
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - images/
    - asset/
